"""obolos rasca y capitulos

Óbolos (saldo en `users` y movimientos), tarjetas de rasca y gana y la fase pendiente de
pago en `stories`. Las cuentas que ya existían reciben la misma bienvenida que una nueva.

Revision ID: 7d3307cbd054
Revises: 91b541cfb075
Fecha: 2026-09-17 13:18:17.748311
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d3307cbd054'
down_revision: Union[str, None] = '91b541cfb075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obolo_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obolo_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obolo_movements_user_id'), ['user_id'], unique=False)

    op.create_table('scratch_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(), nullable=True),
    sa.Column('prize', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('number BETWEEN 1 AND 10', name='ck_scratch_cards_number'),
    sa.CheckConstraint('slot >= 1', name='ck_scratch_cards_slot'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'slot', name='uq_scratch_cards_user_day_slot')
    )
    with op.batch_alter_table('scratch_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scratch_cards_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_phase', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obolos', sa.Integer(), server_default=sa.text('0'), nullable=False))
        # Autogenerate no detecta CHECK en tablas existentes: se añade a mano.
        batch_op.create_check_constraint('ck_users_obolos_no_negativo', 'obolos >= 0')

    # ### end Alembic commands ###

    # Bienvenida a las cuentas existentes. Importe fijo y no `settings.WELCOME_OBOLOS`: una
    # migración debe hacer lo mismo aunque el ajuste cambie después. El filtro la hace
    # idempotente si alguna cuenta ya tuviera su movimiento.
    sin_bienvenida = (
        "id NOT IN (SELECT user_id FROM obolo_movements WHERE reason = 'bienvenida')"
    )
    op.execute(f"UPDATE users SET obolos = obolos + 5 WHERE {sin_bienvenida}")
    op.execute(
        "INSERT INTO obolo_movements (user_id, amount, reason) "
        f"SELECT id, 5, 'bienvenida' FROM users WHERE {sin_bienvenida}"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_obolos_no_negativo', type_='check')
        batch_op.drop_column('obolos')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('pending_phase')

    with op.batch_alter_table('scratch_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scratch_cards_user_id'))

    op.drop_table('scratch_cards')
    with op.batch_alter_table('obolo_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obolo_movements_user_id'))

    op.drop_table('obolo_movements')
    # ### end Alembic commands ###
