"""usuarios dev

Revision ID: 31243aab0559
Revises: e991a62b89c7
Fecha: 2026-09-16 20:22:42.492707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31243aab0559'
down_revision: Union[str, None] = 'e991a62b89c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dev', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_dev')

    # ### end Alembic commands ###
